<!-- Form -->
            <form action="" method="post" id="signin-form_id">
                <div class="signin-text">
                    <span>Recuperar senha</span>
                </div> <!-- / .signin-text -->
                   <?php
                    $flash = $this->flashMessenger();
                    $flash->setMessageOpenFormat('<div%s>
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                            &times;
                        </button>
                        <ul><li>')
                        ->setMessageSeparatorString('</li><li>')
                        ->setMessageCloseString('</li></ul></div>');

                    echo $flash->render('warning',   array('alert', 'alert-dismissible', 'alert-warning'));
                    echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
                    echo $flash->render('success',   array('alert', 'alert-dismissible', 'alert-success'));
                    ?>

                    <div class="alert_show">
                    </div>
                <?php 
                    if($token != false){
                ?>
                        <div class="form-group w-icon">
                            <input type="password" name="senha" class="form-control input-lg" placeholder="Nova senha" id="senha">
                            <span class="fa fa-lock signin-form-icon"></span>
                        </div> <!-- / Username -->

                        <div class="form-group w-icon">
                            <input type="password" name="re_senha" class="form-control input-lg" placeholder="Repetir senha">
                            <span class="fa fa-lock signin-form-icon"></span>
                            <input type="hidden" name="id_user" value="<?php echo $token->id_user;?>"/>
                            <input type="hidden" name="id_token" value="<?php echo $token->id;?>"/>
                        </div> <!-- / Password -->

                        <div class="form-actions">
                            <button  class="signin-btn bg-success btn-alterar-senha" style="margin-right: 10px; margin-top: 5px;">Alterar</button>
                        </div>
                <?}else{ ?>
                    <div class="form-group w-icon">
                        <div class="alert alert-danger">
                            Link expirado
                        </div>
                    </div>
                    <div class="form-actions">
                            <a href="/login" class="signin-btn bg-success" style="margin-right: 10px; margin-top: 5px;">Login</a>
                        </div>
                <?php }?>

            </form>
            <!-- / Form -->