<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="ThemeBucket">
    <link rel="shortcut icon" href="images/favicon.png">

    <title>Login | SS Ponto Fácil</title>

    <!--Core CSS -->
    <link href="<?php echo $this->basePath('assets/css/bootstrap.min.css');?>" rel="stylesheet">
    <link href="<?php echo $this->basePath('assets/css/bootstrap-reset.css')?>" rel="stylesheet">
    <link href="<?php echo $this->basePath('assets/font-awesome/css/font-awesome.css')?>" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="<?php echo $this->basePath('assets/css/style.css'); ?>" rel="stylesheet">
    <link href="<?php echo $this->basePath('assets/css/style-responsive.css'); ?>" rel="stylesheet" />
    <link href="<?php echo $this->basePath('assets/css/login.style.css'); ?>" rel="stylesheet" />
    <link href="<?php echo $this->basePath('assets/css/loader/circle.css'); ?>" rel="stylesheet" />

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]>
    <script src="js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>

  <body class="lock-screen" onload="startTime()">
  <div class="lock-wrapper">

      <div id="time"></div>


      <div class="lock-box text-center">
          <div>
              <div class="alert alert-info alert-dynamic">Efetuando o Login...</div>
          </div>
          <form role="form" class="form-inline" action="" method="post" id="form-login">
              <div class="lock-name">
                  <div class="form-group">
                      <button class="btn btn-lock tooltips" type="button" style="float: left;margin-top: 0.0%;margin-left: 0;" data-placement="top" title="Recuperar senha" href="#myModal" data-toggle="modal">
                          <i class="fa fa-lock"></i>
                      </button>
                      <input placeholder="Usuário" id="usuario" class="form-control lock-input" required="" name="usuario" style="width: 50%;" type="text">
                  </div>
              </div>
              <img src="data/users/img/mot_def.jpg" alt="lock avatar"/>
              <div class="lock-pwd">
                  <div class="form-group">
                      <input type="password" placeholder="Senha" id="senha" class="form-control lock-input" name="senha" required>
                      <button class="btn btn-lock btn-login tooltips" type="submit" data-placement="top" title="Entrar">
                          <i class="fa fa-arrow-right"></i>
                      </button>
                      <button class="btn btn-info btn-entrar" TYPE="button" href="#myModal-1" data-toggle="modal">EXPERIMENTE GRÁTIS</button>
                  </div>
              </div>
          </form>

      </div>
  </div>
  <script>
      function startTime()
      {
          var today=new Date();
          var h=today.getHours();
          var m=today.getMinutes();
          var s=today.getSeconds();
          // add a zero in front of numbers<10
          m=checkTime(m);
          s=checkTime(s);
          document.getElementById('time').innerHTML=h+":"+m+":"+s;
          t=setTimeout(function(){startTime()},500);
      }

      function checkTime(i)
      {
          if (i<10)
          {
              i="0" + i;
          }
          return i;
      }
  </script>

  <!-- Modal -->
  <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade">
      <div class="modal-dialog">
          <div class="modal-content">
              <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h4 class="modal-title">Esqueceu a sua senha?</h4>
              </div>
              <div class="modal-body">
                  <p>Digite o email usado para fazer o registro.</p>
                  <input type="text" name="email" placeholder="Email" autocomplete="off" class="form-control placeholder-no-fix">

              </div>
              <div class="modal-footer">
                  <button data-dismiss="modal" class="btn btn-default" type="button">Cancelar</button>
                  <button class="btn btn-success" type="button">Enviar</button>
              </div>
          </div>
      </div>
  </div>
  <!-- modal -->


    <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal-1" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
                    <h4 class="modal-title modal-register">Experimente grátis por 30 dias e começe a descomplicar sua empresa.</h4>
                </div>
                <div class="modal-body">

                    <form class="form-horizontal form-register" role="form" method="post">
                        <div class="form-group">
                            <label for="inputEmail1" class="col-lg-2 col-sm-2 control-label"></label>
                            <div class="col-lg-10">
                                <h4>Dados Pessoais</h4>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputNome" class="col-lg-2 col-sm-2 control-label">Primeiro Nome</label>
                            <div class="col-lg-10">
                                <input type="text" class="form-control" id="inputNome" name="primeiro_nome" placeholder="">
                            </div>
                        </div>
                         <div class="form-group">
                            <label for="inputLast" class="col-lg-2 col-sm-2 control-label">Sobre Nome</label>
                            <div class="col-lg-10">
                                <input type="text" class="form-control" id="inputLast" placeholder="" name="segundo_nome">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputLast" class="col-lg-2 col-sm-2 control-label">Data de Nascimento</label>
                            <div class="col-lg-10">
                                <input type="text" class="form-control" id="inputBith" placeholder="" name="nascimento">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail1" class="col-lg-2 col-sm-2 control-label"></label>
                            <div class="col-lg-10">
                                <h4>Dados de Acesso</h4>
                            </div>
                        </div>
                         <div class="form-group">
                            <label for="inputEmail" class="col-lg-2 col-sm-2 control-label">Email</label>
                            <div class="col-lg-10">
                                <input type="email" class="form-control" id="inputEmail" placeholder="" name="email">
                            </div>
                        </div>
                         <div class="form-group">
                            <label for="inputUsuario" class="col-lg-2 col-sm-2 control-label">Usuário</label>
                            <div class="col-lg-10">
                                <input type="text" class="form-control" id="inputUsuario" placeholder="" name="usuario">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputSenha" class="col-lg-2 col-sm-2 control-label">Senha</label>
                            <div class="col-lg-10">
                                <input type="password" class="form-control" id="inputSenha" placeholder="" name="senha">
                            </div>
                        </div>
                        <hr>
                        <div class="form-group">
                            <label for="inputEmail1" class="col-lg-2 col-sm-2 control-label"></label>
                            <div class="col-lg-10">
                                <h4>Dados da Empresa</h4>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputRazao_social" class="col-lg-2 col-sm-2 control-label">Razão Social</label>
                            <div class="col-lg-10">
                                <input type="text" class="form-control" id="inputRazao_social" placeholder="" name="razao_social">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputCpf" class="col-lg-2 col-sm-2 control-label">CPF ou CNPJ</label>
                            <div class="col-lg-10">
                                <input type="text" class="form-control" id="inputCpf" placeholder="" name="cpf_cnpj">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputCpf" class="col-lg-2 col-sm-2 control-label">Tipo</label>
                            <div class="col-lg-10">
                                <select class="form-control" name="tipo">
                                    <option value="Pessoa Jurídica">Pessoa Jurídica</option>
                                    <option value="Pessoa Física">Pessoa Física</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputTelefone" class="col-lg-2 col-sm-2 control-label">Telefone</label>
                            <div class="col-lg-10">
                                <input type="text" class="form-control" id="inputTelefone" placeholder="" name="telefone">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEstado" class="col-lg-2 col-sm-2 control-label">Estado</label>
                            <div class="col-lg-10">
                                <select name="estado" class="form-control">
                                    <option value="">Selecione o Estado</option>
                                    <option value="AC">Acre</option>
                                    <option value="AL">Alagoas</option>
                                    <option value="AM">Amazonas</option>
                                    <option value="AP">Amapá</option>
                                    <option value="BA">Bahia</option>
                                    <option value="CE">Ceará</option>
                                    <option value="DF">Distrito Federal</option>
                                    <option value="ES">Espírito Santo</option>
                                    <option value="GO">Goiás</option>
                                    <option value="MA">Maranhão</option>
                                    <option value="MT">Mato Grosso</option>
                                    <option value="MS">Mato Grosso do Sul</option>
                                    <option value="MG">Minas Gerais</option>
                                    <option value="PA">Pará</option>
                                    <option value="PB">Paraíba</option>
                                    <option value="PR">Paraná</option>
                                    <option value="PE">Pernambuco</option>
                                    <option value="PI">Piauí</option>
                                    <option value="RJ">Rio de Janeiro</option>
                                    <option value="RN">Rio Grande do Norte</option>
                                    <option value="RO">Rondônia</option>
                                    <option value="RS">Rio Grande do Sul</option>
                                    <option value="RR">Roraima</option>
                                    <option value="SC">Santa Catarina</option>
                                    <option value="SE">Sergipe</option>
                                    <option value="SP">São Paulo</option>
                                    <option value="TO">Tocantins</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputCidade" class="col-lg-2 col-sm-2 control-label">Cidade</label>
                            <div class="col-lg-10">
                                <input type="text" class="form-control" id="inputCidade" placeholder="" name="cidade">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button type="submit" class="btn btn-lg btn-info float-btn btn-register">Começar</button>
                                <div class="alert alert-danger float-alert alert-register">

                                </div>
                            </div>
                        </div>
                    </form>

                </div>

            </div>
        </div>
    </div>

    <!-- Placed js at the end of the document so the pages load faster -->

    <!--Core js-->
    <script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>"></script>
    <script src="<?php echo $this->basePath('assets/js/bootstrap.min.js')?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.validate.min.js')?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/utility.js')?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/http.js')?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.mask.min.js')?>"></script>/
    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/login/login.controller.js')?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/login/login.view.js')?>"></script>
    <script>
        $(function () {
            $('.tooltips').tooltip()
        })
    </script>
  </body>
</html>
